### ISSUE TITLE
Dependencies not being installed after npm install.

### ISSUE THREAD

**Issue by Kenedy-Henrique** [89netraM/hotheaded-vscode#2]
There is no speaker module at node_modules to do the preparations from https://github.com/89netraM/hotheaded-vscode/blob/master/CONTRIBUTING.md.

I forgot to say that a lot of other modules are being installed but not especially this one.

**Comment by 89netraM** [comment]
Hi! Thank you for your interest in this!

I can't reproduce your problem. Are you running Windows or something else? I know that the `node-speaker` package works differently on Mac and Linux.  
I updated the `node-speaker` package to its latest version, which still require some changes to the definition file, but maybe that will help. Run a `git pull` and try to follow the new [`CONTRIBUTING.md`](https://github.com/89netraM/hotheaded-vscode/blob/master/CONTRIBUTING.md) instructions.

Hope it works, and please keep me updated.

**Comment by Kenedy-Henrique** [comment]
![Screenshot from 2020-09-25 12-31-53](https://user-images.githubusercontent.com/64266887/94329727-ed9d3600-ff93-11ea-9213-e06a099282d8.png)

Looks like is missing some dependency that may be or not relatad to Windows.
Likely some Linux related issue, sorry, I'm layman about it, sorry for not being able to help.

**Comment by 89netraM** [comment]
I think I know what the problem might be. The installation instructions for [`node-speaker`](https://github.com/TooTallNate/node-speaker#installation) says that if you're running Ubuntu (or Debian) you'll need to install [ALSA](https://www.alsa-project.org/wiki/Main_Page) first.

If you clear the `node_modules` folder, then install ALSA with `sudo apt-get install libasound2-dev`, and then try `npm install` again it should work.

If this fixes it I'll rewrite my instructions to include this rather important piece of information.

**Comment by Kenedy-Henrique** [comment]
Now it is working very well thanks for your time.
![Uploading Screenshot from 2020-09-26 15-31-38.png…]()
