### ISSUE TITLE
On windows it only works in version 1.0.0

### ISSUE THREAD

**Issue by Memerguyy** [89netraM/hotheaded-vscode#8]
I have no clue why but for me this only worked when I downgraded to 1.0.0

**Comment by Memerguyy** [comment]
Wait nevermind, I just switched back to 1.1.2 and it worked perfectly. No clue why but it works

**Comment by 89netraM** [comment]
This whole extension is a jumbled mess, I don't know how it works on any version.

Glad it works for you now though. Have fun!
